import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="medium-appbar border-b p-4 flex justify-between">
          <div className="website-logo">Medium Website</div>
          <div className="navigation-items flex">
            <ul className="flex gap-10 mr-4">
              <li>Home</li>
              <li>Blogs</li>
              <li>Contact Us</li>
            </ul>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
