name: Build and Deploy CI/CD Pipeline

on:
  push:
    branches:
      - master

env:
  DOCKER_REPO: ishan091/week-18-class
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker/Dockerfile.user
        push: true
        tags: ${{ env.DOCKER_REPO }}:${{ env.IMAGE_TAG }},${{ env.DOCKER_REPO }}:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new

    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    - name: Verify Pushed Image
      run: docker pull ${{ env.DOCKER_REPO }}:${{ env.IMAGE_TAG }}

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker pull ${{ env.DOCKER_REPO }}:${{ env.IMAGE_TAG }}
          sudo docker stop web-app || true
          sudo docker rm web-app || true
          sudo docker run -d --name web-app \
            -p 3005:3000 \
            --restart unless-stopped \
            ${{ env.DOCKER_REPO }}:${{ env.IMAGE_TAG }}
          sudo docker system prune -af
